# Generated by Django 6.1.1 on 2026-09-05 00:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(default='Indian Institute of Information Technology', max_length=255)),
                ('department', models.CharField(default='Artificial Intelligence & Data Science', max_length=150)),
                ('experience_years', models.IntegerField(default=8)),
                ('immersion_status', models.CharField(default='In-Progress (Intel Labs)', max_length=50)),
                ('fdp_completed_count', models.IntegerField(default=4)),
                ('mentored_students_count', models.IntegerField(default=28)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecruiterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Google Cloud India', max_length=200)),
                ('industry', models.CharField(default='Cloud Computing & AI', max_length=150)),
                ('designation', models.CharField(default='Technical Talent Partner', max_length=150)),
                ('website', models.URLField(blank=True, null=True)),
                ('is_verified_company', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('job_type', models.CharField(choices=[('Internship', 'Internship'), ('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract')], default='Internship', max_length=50)),
                ('location', models.CharField(default='Bengaluru / Hybrid', max_length=150)),
                ('description', models.TextField()),
                ('required_skills', models.JSONField(default=list)),
                ('preferred_skills', models.JSONField(blank=True, default=list)),
                ('salary_or_stipend', models.CharField(default='₹45,000/month', max_length=100)),
                ('openings', models.IntegerField(default=3)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('posted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('recruiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='api.recruiterprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(default='National Institute of Technology', max_length=255)),
                ('branch', models.CharField(default='Computer Science & Engineering', max_length=150)),
                ('year_of_study', models.IntegerField(default=3)),
                ('apaar_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('digilocker_verified', models.BooleanField(default=False)),
                ('cgpa', models.FloatField(default=8.6)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('resume_text', models.TextField(blank=True, null=True)),
                ('placement_probability', models.IntegerField(default=78)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SkillDiagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=74)),
                ('skill_breakdown', models.JSONField(default=dict)),
                ('gaps', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostics', to='api.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='MockInterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_target', models.CharField(default='Full Stack Engineer / AI Specialist', max_length=150)),
                ('questions_answers', models.JSONField(default=list)),
                ('overall_score', models.IntegerField(default=82)),
                ('feedback', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_interviews', to='api.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('REVIEWED', 'Reviewed'), ('SHORTLISTED', 'Shortlisted'), ('INTERVIEW', 'Interview Scheduled'), ('OFFERED', 'Offered'), ('REJECTED', 'Rejected')], default='APPLIED', max_length=50)),
                ('match_score', models.IntegerField(default=85)),
                ('applied_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('recruiter_notes', models.TextField(blank=True, default='')),
                ('timeline', models.JSONField(blank=True, default=list)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='api.job')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='api.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='VerificationQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(default='DigiLocker Academic Credential', max_length=150)),
                ('digilocker_uri', models.CharField(default='in.gov.digilocker:doc:academic-2026-99384', max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved (Verified)'), ('REJECTED', 'Rejected')], default='PENDING', max_length=50)),
                ('submission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='api.studentprofile')),
            ],
        ),
    ]
